import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

interface Kungfu {
  id: number;
  name: string;
  iconId: number;
  color: string;
  textColor: string;
  borderColor: string;
  shortName: string;
}

interface Force {
  id: number;
  name: string;
  kungfus: Kungfu[];
}

interface KungfuData {
  forces: Force[];
}

function generateTypeScript(data: KungfuData): string {
  const martialToSect: Record<string, string> = {};
  const forceNameToId: Record<string, number> = {};
  const kungfuMap: Record<string, number> = {};
  const sectIconIds: Record<string, number> = {};
  const sectConfigs: Record<string, { color: string; textColor: string; borderColor: string; shortName: string }> = {};

  for (const force of data.forces) {
    forceNameToId[force.name] = force.id;
    for (const kungfu of force.kungfus) {
      martialToSect[kungfu.name] = force.name;
      kungfuMap[`${force.id}:${kungfu.name}`] = kungfu.id;
      sectIconIds[kungfu.name] = kungfu.iconId;
      sectConfigs[kungfu.name] = {
        color: kungfu.color,
        textColor: kungfu.textColor,
        borderColor: kungfu.borderColor,
        shortName: kungfu.shortName
      };
    }
  }

  const forcesExport = JSON.stringify(data.forces, null, 2);
  const martialToSectExport = JSON.stringify(martialToSect, null, 2);
  const forceNameToIdExport = JSON.stringify(forceNameToId, null, 2);
  const kungfuMapExport = JSON.stringify(kungfuMap, null, 2);
  const sectIconIdsExport = JSON.stringify(sectIconIds, null, 2);
  const sectConfigsExport = JSON.stringify(sectConfigs, null, 2);

  return `// Auto-generated by vite-plugin-kungfu-data
// Do not edit manually - regenerate with: npm run build

export const FORCES_DATA: Force[] = ${forcesExport} as const;

export const SECT_ICON_IDS: Record<string, number> = ${sectIconIdsExport};

export const SECT_CONFIG: Record<string, SectConfig> = ${sectConfigsExport};

export const MARTIAL_TO_SECT: Record<string, string> = ${martialToSectExport};

export const FORCE_NAME_TO_ID: Record<string, number> = ${forceNameToIdExport};

export const KUNGFU_MAP: Record<string, number> = ${kungfuMapExport};

// 所有心法名称列表（按门派排序）
export const SECTS: string[] = ${JSON.stringify(data.forces.flatMap(f => f.kungfus.map(k => k.name)))};

// 额外的心法（不属于任何门派的通用心法）
// export const EXTRA_SECTS: string[] = [];

export interface Force {
  id: number;
  name: string;
  kungfus: Kungfu[];
}

export interface Kungfu {
  id: number;
  name: string;
  iconId: number;
  color: string;
  textColor: string;
  borderColor: string;
  shortName: string;
}

export interface SectConfig {
  color: string;
  textColor: string;
  borderColor: string;
  shortName: string;
}
`;
}

export default function kungfuDataPlugin() {
  return {
    name: 'vite-plugin-kungfu-data',
    buildStart() {
      const srcDataDir = join(__dirname, 'src', 'data');
      if (!existsSync(srcDataDir)) {
        mkdirSync(srcDataDir, { recursive: true });
      }
    },
    buildEnd() {
      const jsonPath = join(__dirname, 'data', 'kungfu_data.json');
      const outputPath = join(__dirname, 'src', 'data', 'kungfuData.ts');

      const raw = readFileSync(jsonPath, 'utf-8');
      const data: KungfuData = JSON.parse(raw);

      const tsContent = generateTypeScript(data);
      writeFileSync(outputPath, tsContent, 'utf-8');
      console.log('[vite-plugin-kungfu-data] Generated src/data/kungfuData.ts');
    },
  };
}
