// Auto-generated by vite-plugin-kungfu-data
// Do not edit manually - regenerate with: npm run build

export const FORCES_DATA: Force[] = [
  {
    "id": 0,
    "name": "无相楼",
    "kungfus": [
      {
        "id": 10821,
        "name": "幽罗引",
        "iconId": 10821,
        "color": "bg-violet-100 dark:bg-violet-900/30",
        "textColor": "text-violet-700 dark:text-violet-400",
        "borderColor": "border-violet-200 dark:border-violet-800",
        "shortName": "无相楼"
      }
    ]
  },
  {
    "id": 1,
    "name": "少林",
    "kungfus": [
      {
        "id": 10002,
        "name": "洗髓经",
        "iconId": 10002,
        "color": "bg-amber-100 dark:bg-amber-900/30",
        "textColor": "text-amber-700 dark:text-amber-400",
        "borderColor": "border-amber-200 dark:border-amber-800",
        "shortName": "和尚T"
      },
      {
        "id": 10003,
        "name": "易筋经",
        "iconId": 10003,
        "color": "bg-amber-100 dark:bg-amber-900/30",
        "textColor": "text-amber-700 dark:text-amber-400",
        "borderColor": "border-amber-200 dark:border-amber-800",
        "shortName": "和尚"
      }
    ]
  },
  {
    "id": 2,
    "name": "万花",
    "kungfus": [
      {
        "id": 10021,
        "name": "花间游",
        "iconId": 10021,
        "color": "bg-purple-100 dark:bg-purple-900/30",
        "textColor": "text-purple-700 dark:text-purple-400",
        "borderColor": "border-purple-200 dark:border-purple-800",
        "shortName": "花间"
      },
      {
        "id": 10028,
        "name": "离经易道",
        "iconId": 10028,
        "color": "bg-purple-100 dark:bg-purple-900/30",
        "textColor": "text-purple-700 dark:text-purple-400",
        "borderColor": "border-purple-200 dark:border-purple-800",
        "shortName": "花奶"
      }
    ]
  },
  {
    "id": 3,
    "name": "天策",
    "kungfus": [
      {
        "id": 10026,
        "name": "傲血战意",
        "iconId": 10026,
        "color": "bg-red-100 dark:bg-red-900/30",
        "textColor": "text-red-700 dark:text-red-400",
        "borderColor": "border-red-200 dark:border-red-800",
        "shortName": "天策"
      },
      {
        "id": 10062,
        "name": "铁牢律",
        "iconId": 10062,
        "color": "bg-red-100 dark:bg-red-900/30",
        "textColor": "text-red-700 dark:text-red-400",
        "borderColor": "border-red-200 dark:border-red-800",
        "shortName": "天策T"
      }
    ]
  },
  {
    "id": 4,
    "name": "纯阳",
    "kungfus": [
      {
        "id": 10014,
        "name": "紫霞功",
        "iconId": 10014,
        "color": "bg-sky-100 dark:bg-sky-900/30",
        "textColor": "text-sky-700 dark:text-sky-400",
        "borderColor": "border-sky-200 dark:border-sky-800",
        "shortName": "气纯"
      },
      {
        "id": 10015,
        "name": "太虚剑意",
        "iconId": 10015,
        "color": "bg-sky-100 dark:bg-sky-900/30",
        "textColor": "text-sky-700 dark:text-sky-400",
        "borderColor": "border-sky-200 dark:border-sky-800",
        "shortName": "剑纯"
      }
    ]
  },
  {
    "id": 5,
    "name": "七秀",
    "kungfus": [
      {
        "id": 10080,
        "name": "云裳心经",
        "iconId": 10080,
        "color": "bg-pink-100 dark:bg-pink-900/30",
        "textColor": "text-pink-700 dark:text-pink-400",
        "borderColor": "border-pink-200 dark:border-pink-800",
        "shortName": "秀奶"
      },
      {
        "id": 10081,
        "name": "冰心诀",
        "iconId": 10081,
        "color": "bg-pink-100 dark:bg-pink-900/30",
        "textColor": "text-pink-700 dark:text-pink-400",
        "borderColor": "border-pink-200 dark:border-pink-800",
        "shortName": "冰心"
      }
    ]
  },
  {
    "id": 6,
    "name": "五毒",
    "kungfus": [
      {
        "id": 10175,
        "name": "毒经",
        "iconId": 10175,
        "color": "bg-green-100 dark:bg-green-900/30",
        "textColor": "text-green-700 dark:text-green-400",
        "borderColor": "border-green-200 dark:border-green-800",
        "shortName": "毒经"
      },
      {
        "id": 10176,
        "name": "补天诀",
        "iconId": 10176,
        "color": "bg-green-100 dark:bg-green-900/30",
        "textColor": "text-green-700 dark:text-green-400",
        "borderColor": "border-green-200 dark:border-green-800",
        "shortName": "毒奶"
      }
    ]
  },
  {
    "id": 7,
    "name": "唐门",
    "kungfus": [
      {
        "id": 10224,
        "name": "惊羽诀",
        "iconId": 10224,
        "color": "bg-emerald-100 dark:bg-emerald-900/30",
        "textColor": "text-emerald-700 dark:text-emerald-400",
        "borderColor": "border-emerald-200 dark:border-emerald-800",
        "shortName": "鲸鱼"
      },
      {
        "id": 10225,
        "name": "天罗诡道",
        "iconId": 10225,
        "color": "bg-lime-100 dark:bg-lime-900/30",
        "textColor": "text-lime-700 dark:text-lime-400",
        "borderColor": "border-lime-200 dark:border-lime-800",
        "shortName": "田螺"
      }
    ]
  },
  {
    "id": 8,
    "name": "藏剑",
    "kungfus": [
      {
        "id": 10144,
        "name": "问水诀",
        "iconId": 10144,
        "color": "bg-yellow-100 dark:bg-yellow-900/30",
        "textColor": "text-yellow-700 dark:text-yellow-400",
        "borderColor": "border-yellow-200 dark:border-yellow-800",
        "shortName": "藏剑"
      }
    ]
  },
  {
    "id": 9,
    "name": "丐帮",
    "kungfus": [
      {
        "id": 10268,
        "name": "笑尘诀",
        "iconId": 10268,
        "color": "bg-amber-600 dark:bg-amber-900/50",
        "textColor": "text-amber-50",
        "borderColor": "border-amber-500 dark:border-amber-700",
        "shortName": "丐帮"
      }
    ]
  },
  {
    "id": 10,
    "name": "明教",
    "kungfus": [
      {
        "id": 10242,
        "name": "焚影圣诀",
        "iconId": 10242,
        "color": "bg-yellow-100 dark:bg-yellow-900/30",
        "textColor": "text-yellow-700 dark:text-yellow-400",
        "borderColor": "border-yellow-200 dark:border-yellow-800",
        "shortName": "明教"
      },
      {
        "id": 10243,
        "name": "明尊琉璃体",
        "iconId": 10243,
        "color": "bg-yellow-100 dark:bg-yellow-900/30",
        "textColor": "text-yellow-700 dark:text-yellow-400",
        "borderColor": "border-yellow-200 dark:border-yellow-800",
        "shortName": "明教T"
      }
    ]
  },
  {
    "id": 21,
    "name": "苍云",
    "kungfus": [
      {
        "id": 10389,
        "name": "铁骨衣",
        "iconId": 10389,
        "color": "bg-stone-100 dark:bg-stone-900/30",
        "textColor": "text-stone-700 dark:text-stone-400",
        "borderColor": "border-stone-200 dark:border-stone-800",
        "shortName": "苍云T"
      },
      {
        "id": 10390,
        "name": "分山劲",
        "iconId": 10390,
        "color": "bg-stone-100 dark:bg-stone-900/30",
        "textColor": "text-stone-700 dark:text-stone-400",
        "borderColor": "border-stone-200 dark:border-stone-800",
        "shortName": "苍云"
      }
    ]
  },
  {
    "id": 22,
    "name": "长歌",
    "kungfus": [
      {
        "id": 10447,
        "name": "莫问",
        "iconId": 10447,
        "color": "bg-indigo-100 dark:bg-indigo-900/30",
        "textColor": "text-indigo-700 dark:text-indigo-400",
        "borderColor": "border-indigo-200 dark:border-indigo-800",
        "shortName": "长歌"
      },
      {
        "id": 10448,
        "name": "相知",
        "iconId": 10448,
        "color": "bg-indigo-100 dark:bg-indigo-900/30",
        "textColor": "text-indigo-700 dark:text-indigo-400",
        "borderColor": "border-indigo-200 dark:border-indigo-800",
        "shortName": "歌奶"
      }
    ]
  },
  {
    "id": 23,
    "name": "霸刀",
    "kungfus": [
      {
        "id": 10464,
        "name": "北傲诀",
        "iconId": 10464,
        "color": "bg-rose-100 dark:bg-rose-900/30",
        "textColor": "text-rose-700 dark:text-rose-400",
        "borderColor": "border-rose-200 dark:border-rose-800",
        "shortName": "霸刀"
      }
    ]
  },
  {
    "id": 24,
    "name": "蓬莱",
    "kungfus": [
      {
        "id": 10533,
        "name": "凌海诀",
        "iconId": 10533,
        "color": "bg-rose-100 dark:bg-rose-900/30",
        "textColor": "text-rose-700 dark:text-rose-400",
        "borderColor": "border-rose-200 dark:border-rose-800",
        "shortName": "蓬莱"
      }
    ]
  },
  {
    "id": 25,
    "name": "凌雪",
    "kungfus": [
      {
        "id": 10585,
        "name": "隐龙诀",
        "iconId": 10585,
        "color": "bg-cyan-100 dark:bg-cyan-900/30",
        "textColor": "text-cyan-700 dark:text-cyan-400",
        "borderColor": "border-cyan-200 dark:border-cyan-800",
        "shortName": "凌雪"
      }
    ]
  },
  {
    "id": 211,
    "name": "衍天宗",
    "kungfus": [
      {
        "id": 10615,
        "name": "太玄经",
        "iconId": 10615,
        "color": "bg-cyan-100 dark:bg-cyan-900/30",
        "textColor": "text-cyan-700 dark:text-cyan-400",
        "borderColor": "border-cyan-200 dark:border-cyan-800",
        "shortName": "衍天"
      }
    ]
  },
  {
    "id": 212,
    "name": "药宗",
    "kungfus": [
      {
        "id": 10626,
        "name": "灵素",
        "iconId": 10626,
        "color": "bg-teal-100 dark:bg-teal-900/30",
        "textColor": "text-teal-700 dark:text-teal-400",
        "borderColor": "border-teal-200 dark:border-teal-800",
        "shortName": "药奶"
      },
      {
        "id": 10627,
        "name": "无方",
        "iconId": 10627,
        "color": "bg-teal-100 dark:bg-teal-900/30",
        "textColor": "text-teal-700 dark:text-teal-400",
        "borderColor": "border-teal-200 dark:border-teal-800",
        "shortName": "药宗"
      }
    ]
  },
  {
    "id": 213,
    "name": "刀宗",
    "kungfus": [
      {
        "id": 10698,
        "name": "孤锋诀",
        "iconId": 10698,
        "color": "bg-slate-100 dark:bg-slate-900/30",
        "textColor": "text-slate-700 dark:text-slate-400",
        "borderColor": "border-slate-200 dark:border-slate-800",
        "shortName": "刀宗"
      }
    ]
  },
  {
    "id": 214,
    "name": "万灵",
    "kungfus": [
      {
        "id": 10756,
        "name": "山海心诀",
        "iconId": 10756,
        "color": "bg-slate-100 dark:bg-slate-900/30",
        "textColor": "text-slate-700 dark:text-slate-400",
        "borderColor": "border-slate-200 dark:border-slate-800",
        "shortName": "万灵"
      }
    ]
  },
  {
    "id": 215,
    "name": "段氏",
    "kungfus": [
      {
        "id": 10786,
        "name": "周天功",
        "iconId": 10786,
        "color": "bg-violet-100 dark:bg-violet-900/30",
        "textColor": "text-violet-700 dark:text-violet-400",
        "borderColor": "border-violet-200 dark:border-violet-800",
        "shortName": "段氏"
      }
    ]
  }
] as const;

export const SECT_ICON_IDS: Record<string, number> = {
  "幽罗引": 10821,
  "洗髓经": 10002,
  "易筋经": 10003,
  "花间游": 10021,
  "离经易道": 10028,
  "傲血战意": 10026,
  "铁牢律": 10062,
  "紫霞功": 10014,
  "太虚剑意": 10015,
  "云裳心经": 10080,
  "冰心诀": 10081,
  "毒经": 10175,
  "补天诀": 10176,
  "惊羽诀": 10224,
  "天罗诡道": 10225,
  "问水诀": 10144,
  "笑尘诀": 10268,
  "焚影圣诀": 10242,
  "明尊琉璃体": 10243,
  "铁骨衣": 10389,
  "分山劲": 10390,
  "莫问": 10447,
  "相知": 10448,
  "北傲诀": 10464,
  "凌海诀": 10533,
  "隐龙诀": 10585,
  "太玄经": 10615,
  "灵素": 10626,
  "无方": 10627,
  "孤锋诀": 10698,
  "山海心诀": 10756,
  "周天功": 10786
};

export const SECT_CONFIG: Record<string, SectConfig> = {
  "幽罗引": {
    "color": "bg-violet-100 dark:bg-violet-900/30",
    "textColor": "text-violet-700 dark:text-violet-400",
    "borderColor": "border-violet-200 dark:border-violet-800",
    "shortName": "无相楼"
  },
  "洗髓经": {
    "color": "bg-amber-100 dark:bg-amber-900/30",
    "textColor": "text-amber-700 dark:text-amber-400",
    "borderColor": "border-amber-200 dark:border-amber-800",
    "shortName": "和尚T"
  },
  "易筋经": {
    "color": "bg-amber-100 dark:bg-amber-900/30",
    "textColor": "text-amber-700 dark:text-amber-400",
    "borderColor": "border-amber-200 dark:border-amber-800",
    "shortName": "和尚"
  },
  "花间游": {
    "color": "bg-purple-100 dark:bg-purple-900/30",
    "textColor": "text-purple-700 dark:text-purple-400",
    "borderColor": "border-purple-200 dark:border-purple-800",
    "shortName": "花间"
  },
  "离经易道": {
    "color": "bg-purple-100 dark:bg-purple-900/30",
    "textColor": "text-purple-700 dark:text-purple-400",
    "borderColor": "border-purple-200 dark:border-purple-800",
    "shortName": "花奶"
  },
  "傲血战意": {
    "color": "bg-red-100 dark:bg-red-900/30",
    "textColor": "text-red-700 dark:text-red-400",
    "borderColor": "border-red-200 dark:border-red-800",
    "shortName": "天策"
  },
  "铁牢律": {
    "color": "bg-red-100 dark:bg-red-900/30",
    "textColor": "text-red-700 dark:text-red-400",
    "borderColor": "border-red-200 dark:border-red-800",
    "shortName": "天策T"
  },
  "紫霞功": {
    "color": "bg-sky-100 dark:bg-sky-900/30",
    "textColor": "text-sky-700 dark:text-sky-400",
    "borderColor": "border-sky-200 dark:border-sky-800",
    "shortName": "气纯"
  },
  "太虚剑意": {
    "color": "bg-sky-100 dark:bg-sky-900/30",
    "textColor": "text-sky-700 dark:text-sky-400",
    "borderColor": "border-sky-200 dark:border-sky-800",
    "shortName": "剑纯"
  },
  "云裳心经": {
    "color": "bg-pink-100 dark:bg-pink-900/30",
    "textColor": "text-pink-700 dark:text-pink-400",
    "borderColor": "border-pink-200 dark:border-pink-800",
    "shortName": "秀奶"
  },
  "冰心诀": {
    "color": "bg-pink-100 dark:bg-pink-900/30",
    "textColor": "text-pink-700 dark:text-pink-400",
    "borderColor": "border-pink-200 dark:border-pink-800",
    "shortName": "冰心"
  },
  "毒经": {
    "color": "bg-green-100 dark:bg-green-900/30",
    "textColor": "text-green-700 dark:text-green-400",
    "borderColor": "border-green-200 dark:border-green-800",
    "shortName": "毒经"
  },
  "补天诀": {
    "color": "bg-green-100 dark:bg-green-900/30",
    "textColor": "text-green-700 dark:text-green-400",
    "borderColor": "border-green-200 dark:border-green-800",
    "shortName": "毒奶"
  },
  "惊羽诀": {
    "color": "bg-emerald-100 dark:bg-emerald-900/30",
    "textColor": "text-emerald-700 dark:text-emerald-400",
    "borderColor": "border-emerald-200 dark:border-emerald-800",
    "shortName": "鲸鱼"
  },
  "天罗诡道": {
    "color": "bg-lime-100 dark:bg-lime-900/30",
    "textColor": "text-lime-700 dark:text-lime-400",
    "borderColor": "border-lime-200 dark:border-lime-800",
    "shortName": "田螺"
  },
  "问水诀": {
    "color": "bg-yellow-100 dark:bg-yellow-900/30",
    "textColor": "text-yellow-700 dark:text-yellow-400",
    "borderColor": "border-yellow-200 dark:border-yellow-800",
    "shortName": "藏剑"
  },
  "笑尘诀": {
    "color": "bg-amber-600 dark:bg-amber-900/50",
    "textColor": "text-amber-50",
    "borderColor": "border-amber-500 dark:border-amber-700",
    "shortName": "丐帮"
  },
  "焚影圣诀": {
    "color": "bg-yellow-100 dark:bg-yellow-900/30",
    "textColor": "text-yellow-700 dark:text-yellow-400",
    "borderColor": "border-yellow-200 dark:border-yellow-800",
    "shortName": "明教"
  },
  "明尊琉璃体": {
    "color": "bg-yellow-100 dark:bg-yellow-900/30",
    "textColor": "text-yellow-700 dark:text-yellow-400",
    "borderColor": "border-yellow-200 dark:border-yellow-800",
    "shortName": "明教T"
  },
  "铁骨衣": {
    "color": "bg-stone-100 dark:bg-stone-900/30",
    "textColor": "text-stone-700 dark:text-stone-400",
    "borderColor": "border-stone-200 dark:border-stone-800",
    "shortName": "苍云T"
  },
  "分山劲": {
    "color": "bg-stone-100 dark:bg-stone-900/30",
    "textColor": "text-stone-700 dark:text-stone-400",
    "borderColor": "border-stone-200 dark:border-stone-800",
    "shortName": "苍云"
  },
  "莫问": {
    "color": "bg-indigo-100 dark:bg-indigo-900/30",
    "textColor": "text-indigo-700 dark:text-indigo-400",
    "borderColor": "border-indigo-200 dark:border-indigo-800",
    "shortName": "长歌"
  },
  "相知": {
    "color": "bg-indigo-100 dark:bg-indigo-900/30",
    "textColor": "text-indigo-700 dark:text-indigo-400",
    "borderColor": "border-indigo-200 dark:border-indigo-800",
    "shortName": "歌奶"
  },
  "北傲诀": {
    "color": "bg-rose-100 dark:bg-rose-900/30",
    "textColor": "text-rose-700 dark:text-rose-400",
    "borderColor": "border-rose-200 dark:border-rose-800",
    "shortName": "霸刀"
  },
  "凌海诀": {
    "color": "bg-rose-100 dark:bg-rose-900/30",
    "textColor": "text-rose-700 dark:text-rose-400",
    "borderColor": "border-rose-200 dark:border-rose-800",
    "shortName": "蓬莱"
  },
  "隐龙诀": {
    "color": "bg-cyan-100 dark:bg-cyan-900/30",
    "textColor": "text-cyan-700 dark:text-cyan-400",
    "borderColor": "border-cyan-200 dark:border-cyan-800",
    "shortName": "凌雪"
  },
  "太玄经": {
    "color": "bg-cyan-100 dark:bg-cyan-900/30",
    "textColor": "text-cyan-700 dark:text-cyan-400",
    "borderColor": "border-cyan-200 dark:border-cyan-800",
    "shortName": "衍天"
  },
  "灵素": {
    "color": "bg-teal-100 dark:bg-teal-900/30",
    "textColor": "text-teal-700 dark:text-teal-400",
    "borderColor": "border-teal-200 dark:border-teal-800",
    "shortName": "药奶"
  },
  "无方": {
    "color": "bg-teal-100 dark:bg-teal-900/30",
    "textColor": "text-teal-700 dark:text-teal-400",
    "borderColor": "border-teal-200 dark:border-teal-800",
    "shortName": "药宗"
  },
  "孤锋诀": {
    "color": "bg-slate-100 dark:bg-slate-900/30",
    "textColor": "text-slate-700 dark:text-slate-400",
    "borderColor": "border-slate-200 dark:border-slate-800",
    "shortName": "刀宗"
  },
  "山海心诀": {
    "color": "bg-slate-100 dark:bg-slate-900/30",
    "textColor": "text-slate-700 dark:text-slate-400",
    "borderColor": "border-slate-200 dark:border-slate-800",
    "shortName": "万灵"
  },
  "周天功": {
    "color": "bg-violet-100 dark:bg-violet-900/30",
    "textColor": "text-violet-700 dark:text-violet-400",
    "borderColor": "border-violet-200 dark:border-violet-800",
    "shortName": "段氏"
  }
};

export const MARTIAL_TO_SECT: Record<string, string> = {
  "幽罗引": "无相楼",
  "洗髓经": "少林",
  "易筋经": "少林",
  "花间游": "万花",
  "离经易道": "万花",
  "傲血战意": "天策",
  "铁牢律": "天策",
  "紫霞功": "纯阳",
  "太虚剑意": "纯阳",
  "云裳心经": "七秀",
  "冰心诀": "七秀",
  "毒经": "五毒",
  "补天诀": "五毒",
  "惊羽诀": "唐门",
  "天罗诡道": "唐门",
  "问水诀": "藏剑",
  "笑尘诀": "丐帮",
  "焚影圣诀": "明教",
  "明尊琉璃体": "明教",
  "铁骨衣": "苍云",
  "分山劲": "苍云",
  "莫问": "长歌",
  "相知": "长歌",
  "北傲诀": "霸刀",
  "凌海诀": "蓬莱",
  "隐龙诀": "凌雪",
  "太玄经": "衍天宗",
  "灵素": "药宗",
  "无方": "药宗",
  "孤锋诀": "刀宗",
  "山海心诀": "万灵",
  "周天功": "段氏"
};

export const FORCE_NAME_TO_ID: Record<string, number> = {
  "无相楼": 0,
  "少林": 1,
  "万花": 2,
  "天策": 3,
  "纯阳": 4,
  "七秀": 5,
  "五毒": 6,
  "唐门": 7,
  "藏剑": 8,
  "丐帮": 9,
  "明教": 10,
  "苍云": 21,
  "长歌": 22,
  "霸刀": 23,
  "蓬莱": 24,
  "凌雪": 25,
  "衍天宗": 211,
  "药宗": 212,
  "刀宗": 213,
  "万灵": 214,
  "段氏": 215
};

export const KUNGFU_MAP: Record<string, number> = {
  "0:幽罗引": 10821,
  "1:洗髓经": 10002,
  "1:易筋经": 10003,
  "2:花间游": 10021,
  "2:离经易道": 10028,
  "3:傲血战意": 10026,
  "3:铁牢律": 10062,
  "4:紫霞功": 10014,
  "4:太虚剑意": 10015,
  "5:云裳心经": 10080,
  "5:冰心诀": 10081,
  "6:毒经": 10175,
  "6:补天诀": 10176,
  "7:惊羽诀": 10224,
  "7:天罗诡道": 10225,
  "8:问水诀": 10144,
  "9:笑尘诀": 10268,
  "10:焚影圣诀": 10242,
  "10:明尊琉璃体": 10243,
  "21:铁骨衣": 10389,
  "21:分山劲": 10390,
  "22:莫问": 10447,
  "22:相知": 10448,
  "23:北傲诀": 10464,
  "24:凌海诀": 10533,
  "25:隐龙诀": 10585,
  "211:太玄经": 10615,
  "212:灵素": 10626,
  "212:无方": 10627,
  "213:孤锋诀": 10698,
  "214:山海心诀": 10756,
  "215:周天功": 10786
};

// 所有心法名称列表（按门派排序）
export const SECTS: string[] = ["幽罗引","洗髓经","易筋经","花间游","离经易道","傲血战意","铁牢律","紫霞功","太虚剑意","云裳心经","冰心诀","毒经","补天诀","惊羽诀","天罗诡道","问水诀","笑尘诀","焚影圣诀","明尊琉璃体","铁骨衣","分山劲","莫问","相知","北傲诀","凌海诀","隐龙诀","太玄经","灵素","无方","孤锋诀","山海心诀","周天功"];

// 额外的心法（不属于任何门派的通用心法）
// export const EXTRA_SECTS: string[] = [];

export interface Force {
  id: number;
  name: string;
  kungfus: Kungfu[];
}

export interface Kungfu {
  id: number;
  name: string;
  iconId: number;
  color: string;
  textColor: string;
  borderColor: string;
  shortName: string;
}

export interface SectConfig {
  color: string;
  textColor: string;
  borderColor: string;
  shortName: string;
}
